/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaiterRouteImport } from './routes/waiter'
import { Route as PosRouteImport } from './routes/pos'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const WaiterRoute = WaiterRouteImport.update({
  id: '/waiter',
  path: '/waiter',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cashier': typeof CashierRoute
  '/kitchen': typeof KitchenRoute
  '/orders': typeof OrdersRoute
  '/pos': typeof PosRoute
  '/waiter': typeof WaiterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/products': typeof AdminProductsRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cashier': typeof CashierRoute
  '/kitchen': typeof KitchenRoute
  '/orders': typeof OrdersRoute
  '/pos': typeof PosRoute
  '/waiter': typeof WaiterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/products': typeof AdminProductsRoute
  '/api/chat': typeof ApiChatRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cashier': typeof CashierRoute
  '/kitchen': typeof KitchenRoute
  '/orders': typeof OrdersRoute
  '/pos': typeof PosRoute
  '/waiter': typeof WaiterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/products': typeof AdminProductsRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cashier'
    | '/kitchen'
    | '/orders'
    | '/pos'
    | '/waiter'
    | '/admin/analytics'
    | '/admin/products'
    | '/api/chat'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cashier'
    | '/kitchen'
    | '/orders'
    | '/pos'
    | '/waiter'
    | '/admin/analytics'
    | '/admin/products'
    | '/api/chat'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cashier'
    | '/kitchen'
    | '/orders'
    | '/pos'
    | '/waiter'
    | '/admin/analytics'
    | '/admin/products'
    | '/api/chat'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CashierRoute: typeof CashierRoute
  KitchenRoute: typeof KitchenRoute
  OrdersRoute: typeof OrdersRoute
  PosRoute: typeof PosRoute
  WaiterRoute: typeof WaiterRoute
  ApiChatRoute: typeof ApiChatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiter': {
      id: '/waiter'
      path: '/waiter'
      fullPath: '/waiter'
      preLoaderRoute: typeof WaiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CashierRoute: CashierRoute,
  KitchenRoute: KitchenRoute,
  OrdersRoute: OrdersRoute,
  PosRoute: PosRoute,
  WaiterRoute: WaiterRoute,
  ApiChatRoute: ApiChatRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
